# Generated by Django 5.1.3 on 2024-11-29 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars_reviews_app', '0005_noticia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('link', models.URLField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddIndex(
            model_name='noticia',
            index=models.Index(fields=['fecha_creacion'], name='cars_review_fecha_c_e18b19_idx'),
        ),
    ]
