# Generated by Django 5.1.4 on 2024-12-11 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars_reviews_app', '0014_alter_noticiadiferente_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticiadiferente',
            name='img_url',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='other_images/'),
        ),
        migrations.AlterField(
            model_name='noticiadiferente',
            name='link',
            field=models.URLField(max_length=500),
        ),
    ]
